import { Outfit } from 'next/font/google';
import './globals.css';
import "react-toastify/dist/ReactToastify.css";


// 1. Correctly instantiate the font with valid weights
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  // display: 'swap',
  // variable: '--font-outfit',
});
export const metadata = {
  title: 'Blog Application',
  description: 'Generated by create Esraa Saeed',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
      </body>
    </html>
  );
}